spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://tektimesheet.cgdxybxvspry.us-east-1.rds.amazonaws.com:3306/interview_info
    username: tektimesheet
    password: tektimesheet

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
  
logging:
  file: /tmp/logs/myapplication.log

  

  
    
