spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interview_info
    username: root
    password: admin

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
  
    hibernate:
      ddl-auto: create-drop

server:
  port: 8001
  

  
    
